language: java

python:
 
  - "3.7"
  
before_install:  

  wget https://raw.githubusercontent.com/simonowen/pyz80/master/pyz80.py
  
script:

  - ant create-disk -Dpython=python -Dpyz80=pyz80.py
  
deploy:

  provider: releases
  api_key: "4f675cbb9a85257b702c28601413569683b1d97c"
  file: "obj/modplayer.dsk"
  skip_cleanup: true
  on:
    tags: true