language: java

python:
 
  - "3.7"
  
before_install:  

  wget https://raw.githubusercontent.com/simonowen/pyz80/master/pyz80.py
  
script:

  - ant create-disk -Dpython=python -Dpyz80=pyz80.py